version: "3.7"

services:
  drupal:
    image: drupal:8.6
    ports:
      - 8080:80
    depends_on:
      - postgres
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: blah
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  postgres-db: