version: '1.0'
steps:

  build_step:
    type: build
    dockerfile: Dockerfile
    image-name: demochat
    tag: ${{CF_BRANCH}}

  integration_step:
    type: composition
    working_directory: /root/demochat
    composition:
      version: '3'
      services:
        app:
          image: ${{build_step}}
          links:
            - mongo
          ports:
            - 5000
          healthcheck:
            test: ["CMD", "wget", "-q", "http://localhost:5000/"]
            interval: 1m30s
            timeout: 10s
            retries: 3
        mongo:
          image: mongo
    composition-candidates:
      main:
        image: alpine:3.5
        command: sh -c "for i in 1 2 3 4 5; do wget -s -q http://app:5000/ && break || sleep 20; done && wget -s -q http://app:5000/" | echo 'works'
