apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2018-04-06T19:58:30Z","labels":{"name":"demochat"},"name":"demochat","namespace":"bluegreen","resourceVersion":"11889475","selfLink":"/api/v1/namespaces/bluegreen/services/demochat","uid":"e116fa58-39d4-11e8-ba2e-42010a800123"},"spec":{"clusterIP":"10.55.253.63","externalTrafficPolicy":"Cluster","ports":[{"name":"http","nodePort":31082,"port":80,"protocol":"TCP","targetPort":5000}],"selector":{"name":"demochat","version":"223270b"},"sessionAffinity":"None","type":"LoadBalancer"},"status":{"loadBalancer":{"ingress":[{"ip":"35.184.62.129"}]}}}
  creationTimestamp: 2018-04-06T19:58:30Z
  labels:
    name: demochat
  name: demochat
  namespace: bluegreen
  resourceVersion: "11892802"
  selfLink: /api/v1/namespaces/bluegreen/services/demochat
  uid: e116fa58-39d4-11e8-ba2e-42010a800123
spec:
  clusterIP: 10.55.253.63
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 31082
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    name: demochat
    version: 3f41f72
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.184.62.129