apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.Release.Name}}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{.Release.Name}}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{.Release.Name}}
        release: {{.Release.Name}}
        heritage: Tiller
    spec:
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: "{{.Values.imagePullSecret}}"
      {{- end }}
      containers:
      - name: {{.Release.Name}}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        env:
        - name: MONGO_HELM
          value: "{{.Release.Name}}-mongo"

