version: "3.7"

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - webappnetwork

  web:
    build: .
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      MONGO_URI: "mongodb://mongo:27017/exampleDb"
    depends_on:
      - mongo
    networks:
      - webappnetwork

networks:
  webappnetwork:
    driver: bridge